application: straeto-api
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"

handlers:
- url: /data
  static_dir: data
  application_readable: true

- url: .*
  script: main.app